# Generated by Django 5.2.10 on 2026-01-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='demonstration',
            field=models.FileField(default='sign.mp4', upload_to=''),
        ),
    ]
