# Generated by Django 5.2.10 on 2026-01-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='fallback.png', upload_to=''),
        ),
    ]
