# Generated by Django 5.2.10 on 2026-01-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_category_post_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploader',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=75),
        ),
    ]
