# Generated by Django 5.2.10 on 2026-01-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_uploader_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(default='easy', max_length=75),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='defaulthandsign.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='demonstration',
            field=models.FileField(default='defaulthandsignvideo.mp4', upload_to='videos/'),
        ),
    ]
