# Generated by Django 5.2.10 on 2026-02-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_difficulty_alter_post_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='images/defaulthandsign.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='demonstration',
            field=models.FileField(default='videos/defaulthandsignvideo.mp4', upload_to='videos/'),
        ),
    ]
